version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: tasks_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: tasks_redis

  tasks:
    build: 
      context: .
    container_name: tasks_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/tasks/docker/src.sh"]
    ports:
      - 80:80

  celery:
    build:
      context: .
    container_name: tasks_celery
    command: ["/tasks/docker/celery.sh"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0


